set(_CATKIN_CURRENT_PACKAGE "mrobot_imu")
set(mrobot_imu_VERSION "0.0.0")
set(mrobot_imu_MAINTAINER "chenz16 <chenz16@todo.todo>")
set(mrobot_imu_PACKAGE_FORMAT "2")
set(mrobot_imu_BUILD_DEPENDS )
set(mrobot_imu_BUILD_EXPORT_DEPENDS )
set(mrobot_imu_BUILDTOOL_DEPENDS "catkin")
set(mrobot_imu_BUILDTOOL_EXPORT_DEPENDS )
set(mrobot_imu_EXEC_DEPENDS )
set(mrobot_imu_RUN_DEPENDS )
set(mrobot_imu_TEST_DEPENDS )
set(mrobot_imu_DOC_DEPENDS )
set(mrobot_imu_URL_WEBSITE "")
set(mrobot_imu_URL_BUGTRACKER "")
set(mrobot_imu_URL_REPOSITORY "")
set(mrobot_imu_DEPRECATED "")