set(_CATKIN_CURRENT_PACKAGE "mrobot_gps")
set(mrobot_gps_VERSION "0.0.0")
set(mrobot_gps_MAINTAINER "chenz16 <chenz16@todo.todo>")
set(mrobot_gps_PACKAGE_FORMAT "2")
set(mrobot_gps_BUILD_DEPENDS )
set(mrobot_gps_BUILD_EXPORT_DEPENDS )
set(mrobot_gps_BUILDTOOL_DEPENDS "catkin")
set(mrobot_gps_BUILDTOOL_EXPORT_DEPENDS )
set(mrobot_gps_EXEC_DEPENDS )
set(mrobot_gps_RUN_DEPENDS )
set(mrobot_gps_TEST_DEPENDS )
set(mrobot_gps_DOC_DEPENDS )
set(mrobot_gps_URL_WEBSITE "")
set(mrobot_gps_URL_BUGTRACKER "")
set(mrobot_gps_URL_REPOSITORY "")
set(mrobot_gps_DEPRECATED "")